### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Backpackstudio** [phproject-plugins/elasticsearch#11]
500 Internal Server Error
filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated

**Comment by Alanaktion** [comment]
This currently relies on a fairly old version of the elasticsearch library, running `composer update` from the plugin directory may be able to fix it.

**Comment by Backpackstudio** [comment]
Thank you for hint! I will try.

**Comment by Backpackstudio** [comment]
composer update solved issue above, but a new one appeared after that:

```
500 Internal Server Error
No alive nodes found in your cluster [app/plugin/elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51]
```

**Comment by Backpackstudio** [comment]
elasticsearch server configuration issue, not a plugin malfunction.
